#!/usr/bin/env ruby

require 'bundler/setup'

require 'capybara'
require 'capybara/webkit'
require 'capybara/dsl'

<<-COMMENT
*.www.fancyproxy.eu
*.proxyfrance.fr
*.www.notblock.racing
*.bestproxy4u.ml
*.www.shinyproxy.com
*.openwebsite.work
*.elamal.pro
*.bravoproxy.gq
*.isurfer.eu
*.www.proxy-browser-online.net
*.buqd.xyz
*.www.chocolateproxy.eu
*.ironproxy.top
*.pikoslol.ml
*.proxyarab.com
*.www.shinyproxy.eu
*.www.proxygratis.net
*.bypassschool.ga
*.www.ghostproxy.eu
*.345proxy.ml
*.surf4free.ml
*.www.webprotect.pw
*.www.yxorproxy.com
*.fakeip.cf
*.bestproxy.top
*.www.notblock.racing
*.www.districtnewyork.com
*.tomatoproxy.eu
*.securebypassproxy.gq
*.arrestoo.cf
*.www.maddw.com
*.euproxy.org
*.www.netfeed.pw
*.softvpn.ml
*.buqd.xyz
*.bestproxy.bid
*.webproxyserver.info
*.bestproxyserver.info
*.phproxy.work
*.abuomarlive.net
*.88proxy.xyz
*.pr0web.work
*.bestproxy4u.ml
*.multiwebproxy.com
*.odsh.win
*.hideyoufree.cf
*.www.ghostproxy.eu
*.xtcsoul.net
*.otlp.xyz
*.easybrowsing.top
*.firesurfer.ga
*.bvpn.win
*.time2hide.one
*.cloudbypasser.ml
*.fermatfibonacci.info
*.pxfm.xyz
*.europroxy.pw
*.proxyfree.website
*.yavz.xyz
*.phonepiwman.top
*.trucool.ml
*.surf4free.ml
*.access4all.top
*.www.myproxy.bid
*.www.chocolateproxy.eu
*.fasloging.ml
*.superfastsurf.top
*.showvision.info
*.www.gbqr.xyz
*.www.surfingonmyown.com
*.appleleaf.cf
*.topwebproxy.com
*.www.cromcast.net
*.678proxy.ml
*.www.popupfreeproxy.eu
*.ironproxy.top
*.www.hollandproxy.eu
*.www.proxy-browser-online.net
*.brokenleg.cf
*.flash-proxy.com
*.securesurf.ml
*.pzou.win
*.www.freewebproxyserver.pw
*.webproxy.to
*.webrowserfree.top
*.worka.work
*.0proxy.space
*.voslokj.ml
*.booklof.cf
*.8proxy.space
*.charlieproxy.ml
*.www.superproxy.eu
*.bravoproxy.gq
*.www.myfastproxy.eu
*.www.unblock-youtube.eu
*.proxyforeu.org
*.netherlandsproxyserver.club
*.www.web-site.review
*.superproxy.win
*.sokrat.ml
*.protectfreedom.top
*.www.proxygratis.net
*.1luvproxy.cf
*.topproxy.ml
*.bestfreessl.top
*.www.hidesurfproxy.ml
*.dontblameme.ga
*.openwebsite.work
*.www.proxymist.com
*.www.bananaproxy.eu
*.konchap.com
*.accessproxy.org
*.fastproxyweb.com
*.easyhide.top
*.5proxy.space
*.pikoslol.ml
*.afww.xyz
*.imtheone.top
*.surfandgo.win
*.proxyisp.com
*.launchitnow.top
*.freesite.work
*.nomorewait.top
*.hidemefast.top
*.kproxy.info
*.secretproxy.org
*.4freeproxyserver.com
*.proxyfree.party
*.franceproxy.pw
*.456proxy.ml
*.www.ooproxy.pw
*.www.hispaproxy.eu
*.androidnicheman.info
*.fakeip.cf
*.unlockus.ga
*.buka.link
*.cijq.xyz
*.www.yxorproxy.com
*.www.webprotect.pw
*.lighitspeedproxy.top
*.dacd.win
*.invisiblesurf.review
*.newip.win
*.www.proxyzan.info
*.www.gizlen.net
*.proxyfree.asia
*.unblockwebsites.net
*.openall.ml
*.789proxy.cf
*.freeserverproyx.ml
*.www.proxygratis.es
*.www.fancyproxy.eu
*.pouf.win
*.supervpn.top
*.www.predecessor.info
*.www.shinyproxy.eu
*.freevpn4u.ml
*.wordwildprox.ml
*.fedexy.ga
*.kifkifgo.ml
*.youtubeunblocker.us
*.mainproxy.pw
*.newidentity.win
*.bsake.com
*.useitfree.top
*.avpn.win
*.www.befreeproxy.com
*.proxyeuro.pw
*.takomakovpn.top/
*.www.stealthproxy.eu
*.345proxy.ml
*.www.proproxy.me
*.proxyfrance.fr
*.faridy.ga
*.surfingfree.ml
*.07browsethe.website
*.daily-web-proxy.blogspot.com.au
*.hkwebproxy.com
*.proxynator.com
proxynator.com
*.sweetproxies.com
*.proxidox.com
*.proximox.com
*.proxiza.com
*.airtelproxy.com
*.proxy-secure.com
*.imediaproxy.com
*.askproxy.com
*.geek-proxy.com
*.java-proxy.com
*.ksproxy.com
*.torproxy.be
*.thtproxy.com
*.swatproxy.com
*.proxy-http.com
*.sokoproxy.com
*.weboroxy.com
*.2014proxy.com
*.topoproxy.com
*.byproxy.be
*.proxybrid.com
*.sporoxy.com
*.inbloxy.com
*.ksproxy.com
*.911proxy.net
*.traderpro.be
*.fastproxy.be
*.the-firewall.com
*.allonokia.net
*.youtube-proxy.info
*.yallaface.net
*.inproxy.info
*.ipunblocker.net
*.azproxy.net
*.zendproxy.net
*.katavax.com
*.dayproxy.net
kritovana.urhostz.org
p3rso.ns11-wistee.fr
*.proxysitelist.net
*.mejorproxy.com
*.schoolbypasser.gq
*.starprivacy.com
*.surfsafely.com
www.filterbypass.me
www.proxfree.com/proxy
free-proxyserver.com
unblock-proxy.com
www.proxysite.com
Hidemyass.com
Proxify.com
freeopenproxy.com
proxy2014.net
unblockyoutubefree.net
www.kproxy.com
www.blewpass.com
zendproxy.com
4everproxy.com
www.unblockmyweb.com
youtubeunblockproxy.com
vtunnel.com
proxy.org
newipnow.com
ninjacloak.com
anonymouse.org
www.anonymizer.com
defilter.us
freeproxyserver.uk
freeyouproxytube.com
webproxy.net
workingproxy.net
freeyoutube.net
www.vobas.com
www.dontfilter.us
fastusaproxy.com
youtubefreeproxy.net
proxyo.info
rapidproxy.us
unblockyoutubeatschool.com
hidingyour.info
unblocker.us
quickproxy.co.uk
thebestproxy.info
ecxs.asia
justproxy.co.uk
proxy-2014.com
vpnbrowse.com
proxyone.net
webproxyfree.net
cantblockthis.org
hidetheinternet.com
greatestfreeproxy.com
www.proxay.co.uk
viewyoutube.net
pro-unblock.com
hidemytraxproxy.ca
workingproxy.net
stardollproxy.com
strangermeetup.com
02browsewith.pw
06usevpn.website
1-0-1.gq
1.malabarbichette.fr
1.proxysitesunblock.com
1001proxy.com
101proxy.gq
10browsewith.pw
123proxy.org
123proxy.webcam
12usevpn.website
130yom.com
14proxy.com
16usevpn.website
17usevpn.website
18browsethe.website
18usevpn.website
19usevpn.website
1proxy.bid
1proxy.ninja
1proxy.science
1proxy.work
2.meubelencoch.be
20browsethe.website
20usevpn.website
2proxy.xyz
3proxy.xyz
4proxy.xyz
5proxy.xyz
6-proxy.gq
666proxy.gq
6proxy.xyz
9oo9le.gq
a-itc.be
abuomarlive.net
accessanonymous.info
accessed.gq
accessite.gq
accessproxy.gq
accessproxy.org
accessproxy.science
activeconnect.info
activeproxy.gq
activeproxys.gq
activewebproxy.ga
adsenseclickshare.com
adultsexproxy.com
africahide.info
agentfree.work
agentssl.info
ahuforums.com
all-of-proxy.com
allhidden.tk
allinproxy.gq
allnewproxy.gq
ameer99.tk
amproxy.tk
analystefinancier.win
anewproxy.cf
anewproxy.ml
ankracet.com
anonpass.ga
anonymoushit.info
anonymousproxy.cf
anonymoussurfer.xyz
anonymousunblocker.gq
anonymsurf.xyz
antblocks.com
app-proxy.co.uk
appschool.info
appsunblock.info
aproxy.work
arabproxy.gq
arenasecure.info
asiaproxy.info
atwork.info
autohide.info
autotunnel.info
avaliableproxy.ml
b-itc.be
back2proxy.tk
badil24.com
baper.pw
barakouda.ml
barioxy.gq
basicsproxy.info
be-free.gq
beinternet.info
best-proxy-for-you.cu.cc
best.ruouvangnhatrang.com
bestagent.work
bestbuzstore.info
besthide.gq
bestman.gq
bestproxies.gq
bestproxxy.co.vu
bestproxy.work
bestproxys.ga
bestproxyserver.ml
bestproxysolution.com
bestproxysolution.xyz
bestproxyweb.ga
bestroxy.gq
bestserversite.fav.cc
bestwebproxy.ga
bestwebproxy.party
bestwebsurfer.gq
bestwebunlocker.ga
biba-surf.co.uk
bitshidden.info
bitswork.info
blackwaleed.com
blankbrowse.com
bleachproxy.tk
bonproxy.tk
break-the-wall.gq
breaker-proxy.com.ve
bring12.3eeweb.com
bsake.com
btyproxy.com
businessanonymous.info
bvvnb.gq
bypasser.info
bypassfilterproxies.ml
bypassfilterproxy.gq
bypassfilterproxy.ml
canproxy.gq
cantseeme.tk
caproxy.gq
careweb.info
chatffree.cf
chatffree.ga
chatffree.gq
chatffree.ml
chatinschool.cf
chatrx.gq
cintica.nl
circlesecure.info
cityunlock.info
claroxyvisul.gq
clickprivate.info
cloaker.top
cloudproxy.space
colaprox.gq
connectauto.info
coolproxie.tk
coolproxy.gq
cser.ren
cyx07.el3oumda.com
d-itc.be
dailybypass.gq
dailyonline.info
dakiro.top
datanet.gq
deproxy.pw
derproxy.com
dertyghour.gq
designteamgroup.info
diabetestype1answers.com
digitalgeo.info
digitalsoftware.info
directproxy.info
domainssl.info
domroxy.gq
doriytxer.gq
dreamproxies.com
dwba.tk
easy-fast-proxy.website
easy-prox.com
easy-proxy.com.ve
easy.gq
easyproxies.gq
easysurf.gq
el-proxy.gq
elamal.pro
elfarcha.com
emerproxy.site88.net
emerproxy.xyz
erp-itc.be
eskpress.com
estisherer.ml
euproxy.org
everyroxy.gq
ex-adsense.com
exiost.com
f-itc.be
f-proxy.gq
fabulous3.com
facebook-unblock.com
fast-free-proxy.gq
fast-proxy.pw
fast-proxy.webcam
fast-unblock-site.info
fast-web-proxy.gq
fast-web-surf.gq
fast-webproxy.gq
fastair.info
fastanywhere.info
fastbypass.gq
faster-pro.appspot.com
fastestgate.appspot.com
fastmania.net
fastp.net
fastproxy.gq
fastproxy.top
fastproxysite.co.vu
fastserver.fav.cc
fastsurf.win
fastunblocker.tk
fastvpnproxy.science
fastweb.club
fastwebschool.com
fbsurf.party
fcroxy.gq
fdaih.com
fgrezsyt.gq
fictory.gq
filed.gq
filterbypass.xyz
filterbypasser.ml
findproxys.gq
findproxysites.gq
finishid.gq
fivestar.gq
flash-proxy.com
fopurroxy.gq
forja4d.com
forsurf.gq
fproxy.co.vu
fproxy.net
fpx0.com
fraghost.gq
fredzot.gq
free-fast-proxy-server.gq
free-fast-proxy.co
free-fast-proxy.gq
free-fast-proxy.info
free-fast-proxy.science
free-good-proxy.gq
free-proxxy.cf
free-proxxy.ga
free-proxxy.gq
free-proxxy.ml
free-proxxy.tk
free-proxy-jumper.com.ve
free-proxy-server.pw
free-proxy-site.webcam
free-proxy-web-server.info
free-proxy.ml
free-proxy.party
free-proxy.pw
free-proxy.site
free-proxy.webcam
free-proxysites.win
free-web-proxy-server.gq
free-web-proxy.cf
free-web-proxy.cricket
free-web-proxy.gq
free-web-proxy.party
free-web-proxy.pw
free-web-proxy.space
free-web-server.date
free-web-surfing.party
free-web.gq
free-webproxy.gq
free.uxblu.com
freeandbest.gq
freeanonymousproxy.xyz
freecost.gq
freedom4proxy.com
freedomproxy.gq
freeeasyproxysite.webcam
freeedom.gq
freeer.club
freefranceproxy.cf
freeip.co
freeiplist.xyz
freeips.ml
freeopenproxy.webcam
freeost.gq
freeproxies.top
freeproxxy.co.vu
freeproxy.blue
freeproxy.click
freeproxy.host
freeproxy.party
freeproxy.racing
freeproxy.win
freeproxy.work
freeproxyserver.win
freeproxyserver.xyz
freeproxysite.co.vu
freeproxysite.date
freeproxysite.ml
freeproxysite.racing
freeproxysite.us
freeproxysurfing.gq
freeproxyus.work
freeproxyweb.ga
freery.gq
freeserver.website
freesite.work
freesurf.nl.ai
freesurfer.ml
freesurfproxy.ga
freeunblock.gq
freeunblock.science
freeunblocker.cf
freeunblocker.ga
freeunblocker.gq
freeunblocker.ml
freeurl.site
freew.bid
freewb.loan
freeweb.party
freewebproxy.club
freewebproxy.party
freewebproxyserver.pw
freeyt.fr.to
frenchident.tk
fresh-proxy.gq
freshproxy.ga
freshproxy.ml
freshproxyserver.cf
fridays.gq
fuckroxy.gq
fullhidden.com
fullproxie.tk
fullunblock.tk
furthersearchonline.info
gamesnow.fav.cc
gateproxy.pl
gbproxy.pw
geekweb.top
geely.gq
getaccess.gq
gethide.net
getip.cf
getip.gq
getnewip.gq
getpass.xyz
getvpn.cf
getvpn.ga
ghfggj.gq
ghostme.review
ghostsurf.gq
globaltv24h.com
gobye.science
goday.site
gofreeprox.nl.ai
golding-server.com
golding-server.eu
goldproxylist.com
goo-proxy.com
gooday.gq
goodproxy.party
goodproxy.science
goodproxy.webcam
goopenit.com
gowebsurf.gq
gratisspela.com
gratisvpn.ga
gratuiroxy.gq
gratuitroxy.gq
greatproxy.work
gulfzoo.net
happyproxy.ml
hayproxy.gq
helloman.gq
helloproxy.science
helproxy.tk
hereizroxy.gq
hereyourroxy.gq
hi5proxy.com
hida.xyz
hidden4ever.tk
hidden4me.tk
hiddenactive.info
hiddencare.info
hiddeninternet.cf
hiddeninternet.ga
hiddenvisit.gq
hiddenworld.cf
hiddenworld.ga
hide-ip.us
hide-my-ip.gq
hide-my-ip.review
hide-my-ip.science
hideaccess.info
hidebrain.info
hidedirect.us
hidefromyou.com
hideing.bid
hideipsurfing.gq
hideit.xyz
hidemoi.xyz
hidemyasse.ga
hidemyip.info
hidemyip.xyz
hidenipproxy.gq
hideproxyfree.com
hideproxys.ml
hider.link
hider.pw
hider.xyz
hiderealip.net
hidesurfer.ga
hidetunnel.gq
hideussurf.cf
hidewebproxy.ml
high-value-proxy.gq
hiproxy.net
hiroxy.gq
hitproxy.us
hokriroy.gq
holleman.gq
hostprivate.info
hot-free-proxy.gq
hot-proxy.gq
hot-proxy.science
hotelfast.info
hotproxy.science
httproxy.gq
hurryproxy.tk
hyveproxy.net
i-geek.gq
i-invisible.gq
ikproxy.com
ilhamroxy.gq
ilovyou.gq
imhidden.tk
imorach.com
ineedproxy.gq
internetaction.info
internetbytes.info
internettunnel.info
internetunblock.gq
iphide.tk
iproxy.tech
ipstash.com
ipunblock.net
ipunblocker.tk
isurf.gq
itproxy.work
iwantproxy.com
jackproxy.com
javierroxy.gq
jproxy.gq
karizma.gq
kaza4web.com
keephidden.tk
kickass-proxy.gq
kingdomproxy.ga
kingproxy.ga
kommenroxy.gq
kopites.club
kops.club
letmehide.info
letushide.ga
lifefree.gq
lifewithroxy.gq
lighton.gq
limiteless.com
livelynetwork.com
llopisagario.biz
loginroxy.gq
looool.gq
lopiko.top
loveb.science
loveroxy.gq
lowproxy.bid
m-itc.be
macinternet.info
magicprox.com
mapp4u.com
maxprotect.net
meega.webcam
megahot.gq
mehwer.com
mem8.com
mendem.cf
milk-proxy.com
miroxy.gq
mlproxy.science
mmboy.party
modification.xyz
modigital.info
moneca.gq
mproxy.ml
mr-proxy.gq
mrunblocked.tk
mrunblocker.tk
mxtime.party
my-proxy-server.gq
my-proxy.ovh
my-web-proxy.gq
mybinbin.science
myfreeproxy.gq
mymystic.info
mypro.pub
myproxy.bid
myproxy.site
myproxy.win
myroxy.gq
mytimepreferred.info
myunblockeronline.info
nameconnect.info
narutoproxy.tk
navigateallsites.com
ncproxy.com
needproxy.gq
netfeed.pw
netherlandsproxy.pw
netproxy.gq
new-proxy.gq
new-web-proxy.gq
newbie2expert.com
newbor.site
newfreeproxys.gq
newhideproxy.gq
newpp.party
newpro.info
newproxxy.co.vu
newproxy.party
newproxy2016.cf
newproxys.com
newproxyweb.ga
newproxyweb.gq
newroxy.gq
newroy.gq
newunblocker.gq
newunblocker.ml
newvpn.cf
newvpn.ga
newvpn.gq
newvpn.ml
newweb.gq
newwebproxy.ml
newyer.site
nextisnow.gq
nicewebs.co.uk
nicewebs.xyz
ninjasurfer.xyz
no1proxy.gq
nopay.party
noproxyads.com
notblock.gq
notblock.racing
nproxy.ml
nqma.net
nroxy.com
nvh33.com
o-itc.be
oitc.be
oneone.gq
oneproxing.gq
onethree.gq
onlinebrowser.gq
onlinefreeproxy.com
onlineplay.info
onlineproxy.cf
onlineproxybrowser.net
onlineproxysite.cf
onlinesurf.info
onmy.gq
ooproxy.pw
open-germany.com
openblockedwebsites.net
openwebproxy.ga
openwebsite.gq
opnitnow.com
opnitnow.info
oproxy.ml
oprxop.gq
osis.pw
ouadsouss.com
outs.site
p-r-o-x-y.info
pageonline.info
pan.one
panyuxin.com
passiveproxy.com
pazou.xyz
perfectproxie.tk
personalproxyserver.blogspot.com
phunu300.com
plants-vs-proxy.gq
polito.top
powerproxies.com
powerproxy.com.br
premiumproxy.gq
prieroxy.gq
privacysurf.gq
privatebrowser.in
privateip.win
privatemobile.info
privateproxy.xyz
privatesurf.gq
prixofroxy.gq
proesk.tk
proo88.com
proopen.info
prooxy.in
propro.link
protectproxys.cf
provip.club
proxana.pro
proxhunter.tk
proxie.date
proxie.win
proxies.gq
proxiesite.tk
proximusfreedom.com
proxpro.42t.com
proxsite.ga
proxsites.tk
proxxxi.co.vu
proxxy.work
proxy-arabic.com
proxy-browser-online.net
proxy-for-all.xyz
proxy-home.com
proxy-server.pw
proxy-site.c0.pl
proxy-site1.info
proxy-site1.net
proxy-wars.com
proxy.malabarbichette.fr
proxy.ruouvangnhatrang.com
proxy2016.net
proxy20166.blogspot.com
proxy2017.com
proxy2050.tk
proxy2u.com
proxy4all.space
proxy4free.party
proxy4surfing.ga
proxy4surfing.ml
proxyablesschool.com
proxyage.info
proxyanblocker.com
proxyanonymous.cf
proxyaw.com
proxybrowser.ga
proxyde.net
proxyfield.com
proxyforeu.org
proxyforfr.org
proxyforschools.com
proxyforu.gq
proxyfree.asia
proxyfree.gq
proxyfree.party
proxyfree.pw
proxyfree.space
proxyfree.website
proxyfreegate.com
proxyfuse.com
proxygate.pl
proxyguru.science
proxyhome.gq
proxyhome.ml
proxyhut.gq
proxyioz.nz
proxylist2016.com
proxylistweb.com
proxyman.science
proxyme.info
proxymist.com
proxymore.com
proxymos.com
proxynor.com
proxyplus.ml
proxyprofit.tk
proxyreverse.ml
proxyrocket.org
proxys.ga
proxyschool.gq
proxysite.work
proxysitess.com
proxysitess.ml
proxysitesunblock.com
proxytunnels.ml
proxyunblock.info
proxyunlocker.gq
proxyus.ga
proxyusa.org
proxyweb.in
proxyweb.ml
proxyweb.site
proxyweb.top
proxyworld.org
proxyz.gq
proxyzone.org
prx.3space.info
prx5.coxslot.com
prxe.honor.es
prxusa.coxslot.com
prxyoussef.com
pspeed.ga
qonseil.com
queenproxy.gq
quickproxy.gq
quickproxy.science
rafkatproy.gq
ragadaroxy.gq
rapidproxy.me
rapidroxy.gq
razalla.com
realads.mobi
recentproxys.gq
redsite.info
reenroxy.gq
refreshpage.org
reservergroup.com
reversproxy.com
rijem.com
ronroxy.gq
rose.gq
roxygratuit.gq
roxyman.gq
roxyproy.gq
roxyroxy.gq
royfinishid.gq
rrproxy.pw
rtime.club
runroxy.com
s-itc.be
safebrowsing.top
safehide.cf
safeproxysurf.ga
safeproxysuring.gq
safetysurf.cf
sanop.gq
schoolbypass.cf
schoolbypass.gq
schoolbypasser.gq
schoolbypasser.ml
schoolpub.info
schoolxcess.com
secretproxy.org
secureace.info
securebypassproxy.gq
securefreedom.gq
securegeek.info
securehidden.cf
securehidden.gq
secureinternet.info
sedhat.ga
seedhaat.gq
seen.gq
servermonitor.tech
sevensurf.gq
share-proxy.net
shareproxy.gq
shenme.science
shieldproxy.net
shokrit.gq
showgirl2015.top
showpr.club
showproxy.gq
showvision.info
showwhy.science
sikoprox.gq
simojro.gq
simoproxy.tk
sinproxy.com
siompyor.gq
siteeasy.info
sitefree.trade
siteproxy.gq
sitesocial.info
siteunblocker.xyz
skinftw.com
smartwebproxy.ga
sohidden.tk
sounblocked.tk
spain-server.com
spain-server.eu
specialproxy.gq
speed-proxy-server.gq
speed-proxy.gq
speed-server.gq
speedproxy.gq
speedproxy.party
speedproxy.science
speedproxyserver.gq
speedsurf.faith
speedsurf.gq
speedsurfer.ml
spy.pink
sslbasics.info
startvpn.info
stealthed.cc.vg
stealthed.id.ai
stealthed.uk.ht
stealthed.ws.gy
stealthed.xyz
stealthed.ye.vc
suaproxy.site
suferproxy.ml
supps-00.appspot.com
surf-fast.me
surf-web.gq
surfanon.me
surfbyproxy.com
surfdigital.info
surfer-proxy.com.ve
surfo.info
surfonlineanonymous.gq
surfprivacy.gq
surfpro.info
surfproxy.gq
surfsite.gq
surfwebproxy.gq
svfroxy.gq
sweden-proxy.com
sweden-proxy.eu
tabproxy.gq
takeproxy.net
techunblock.info
teke.gq
teleport.to
tenten.gq
testpro.info
testpronn.fav.cc
the-1-of-server.com
the-france-proxy.com
the-france-proxy.eu
the-king-proxy.com
thefastproxy.nl.ai
thefreeproxxy.cf
thefreeproxxy.ga
thefreeproxxy.gq
thefreeproxxy.ml
thefreeproxxy.tk
thefreeproxy.ga
thegoodproxy.cf
thegoodproxy.ga
thegoodproxy.gq
thegoodproxy.ml
thegoodproxy.tk
thehidenproxy.cf
thehidenproxy.gq
thehidenproxy.ml
thehidenproxy.tk
thepf.tk
theproxysite.net
theproxyweb.com
toet.ga
topaproxy.tk
topproxysite.tk
topwebproxies.cf
topwebproxy.com
tosurf.online
totoproxy.gq
tradermarocain.win
trproxy.gq
tryvpn.cf
tryvpn.gq
tttset.party
tunnelcloud.info
tunnelhome.info
tunnelonline.info
turbonet.io
turboproxy.gq
uk-ip.gq
uk-proxy.us
un-blockit.com
unbblocksc.cf
unbblocksc.ga
unbblocksc.gq
unbblocksc.ml
unblock-youtube.com.ve
unblock.meubelencoch.be
unblock1.cf
unblock1.ga
unblock1.gq
unblock1.ml
unblockall.top
unblockandsurf.com
unblockanything.cf
unblockanything.ga
unblockanything.ml
unblocked.download
unblockedsiteproxy.ml
unblockedunblockproxy.party
unblockedworld.cf
unblockedworld.gq
unblocker.space
unblocker1.cf
unblocker1.ga
unblocker1.gq
unblocker1.ml
unblockers.ml
unblockerweb.cf
unblockerweb.ga
unblockerweb.gq
unblockerweb.ml
unblockhost.info
unblocking.gq
unblockip.tk
unblockit.me
unblockit.webcam
unblockmedia.cf
unblockmedia.ga
unblockmedia.gq
unblockmedia.ml
unblockmovies.gq
unblockproxies.ml
unblockproxy.gq
unblocks.pub
unblockshool.party
unblocksites.cf
unblocksites.ga
unblocksites.gq
unblocksites.tech
unblocksites.work
unblocksocialsite.com
unblocktwice.cf
unblocktwice.ga
unblocktwice.gq
unblocktwice.ml
unblockvideo.cf
unblockvideo.ga
unblockvideo.gq
unblockvideo.ml
unblockweb.ga
unblockweb.party
unblockwebsite.date
unblockwebsite.gq
unblockwebsite.work
unblockwebsites.us
unblockyou.net
unblockyoutube.xyz
unblokyoutue.cf
unblokyoutue.ga
unblokyoutue.gq
unblokyoutue.ml
unhide.link
unlockedweb.ml
unlockmyweb.gq
unlockpro.info
unlockproxypro.com
unlockus.cf
unlockus.ga
unlockwebsites.gq
unlockyoutube.xyz
unroxy.uk
urlcut.link
urlfree.gq
usproxy24.com
uuproxy.pw
uxblu.com
v-itc.be
venusfactoreviews.com
video-proxy.party
video4proxy.tk
viva-me.gq
vividproxy.com
vpn-proxy.webcam
vpnactive.info
vpnagent.info
vpnforeveryone.ml
vpnproxy1.com
vpnwebsite.ml
vpsproxy.com
vvproxy.pw
walikanlmohim.tk
wawaproxy.gq
web-proxies.cf
web-proxies.gq
web-proxy.party
web-proxy.pw
web-proxy.win
web-site.review
web-sites.gq
web4free.science
web4proxy.gq
webbasedproxy.gq
webbypassproxy.ga
webf.top
webfreeproxy.science
webpp.club
webpp.link
webprotect.pw
webproxi.xyz
webproxy.gq
webproxy.party
webproxy.racing
webproxy.win
webproxy.work
webproxy4free.info
webproxyhide.gq
webproxylist.net
webproxyserver.cf
webproxyserver.gq
webproxysites.gq
webproxysurf.info
webproxysurfing.cf
webroxy.gq
websky.xyz
webweb.pub
whyboy.science
wiprox.co.uk
workarena.info
workingproxies.gq
workingproxy.gq
workproxyus.ml
workt.work
wproxy.tk
wwp.scottexteriors.com
wwp.tesna.net
wwp.yuktha.com
wwproxy.pw
wwwproxy.gq
x-s-x.gq
xbody.ninja
xeronet.comlu.com
xeronet.netau.net
xeronet.netne.net
xeronet.site88.net
xnpics.cf
xtcsoul.net
yesfreedom.gq
yesproxy.gq
yesproxy.nl.ai
yesroxy.ga
yesroyt.gq
yoha.science
yourproxy.club
yourproxy.party
yourproxy.webcam
yourspeed.gq
youtubeunblocked.cf
yr-proxy.com
yroxy.com
yrproxy.com
yyproxy.pw
zeroproxy.gq
zinproxy.tk
ziproxy.top
zoeken.gq
  unblocken.com
  kik.com
  ninjaweb.xyz
4everproxy.com
www.dailyproxylist.com
xsproxy.com
skinftw.com
dailybypass.gq
surfo.info
phunu300.com
mapp4u.com
torrentcrazy.worldproxy.eu
freesurfproxy.cf
unblockyou.ga
unblockyoutube.online
hideipsurfer.ga
freebypass.gq
surfin.club
proxy4access.ga
freeproxyclub.com
usabypasser.gq
unblock-website.top
unblockyoutube.online
hideipsurfer.ga
freebypass.gq
surfin.club
proxy4access.ga
freeproxyclub.com
usabypasser.gq
unblock-website.top
topproxys.gq
newproxyhide.gq
surfo.info
dailybypass.gq
freesurfproxy.cf
activeproxys.gq
safeproxys.cf
surfwebproxy.gq
mapp4u.com
phunu300.com
globaltv24h.com
fastbypass.gq
hideproxyfree.com
newunblocker.gq
safeproxysurf.ga
freesurfproxy.ga
hideussurf.cf
suferproxy.ml
newhideproxy.gq
findproxysites.gq
bestproxyweb.ga
openwebproxy.ga
happyproxy.ml
hiddeninternet.cf
bestnewproxy.gq
onlineproxysite.cf
allnewproxy.gq
smartwebproxy.ga
hiddeninternet.ga
anewproxy.cf
activewebproxy.ga
urlcut.link
anewproxy.ml
proximusfreedom.com
avaliableproxy.ml
webbypassproxy.ga
skinftw.com
topwebproxies.cf
schoolbypasser.gq
unlockmyweb.gq
hideusproxys.ga
surfbyproxy.cf
kopites.club
webproxyhide.gq
unlockedweb.ml
cloaker.top
securehidden.gq
securehidden.cf
emerproxy.xyz
nqma.net
unblockschool.gq
hideipsurfing.gq
sw0rdfish.de
uswebproxy.ml
proxyisp.com
getproxi.es
franceproxy.gq
surfhidden.gq
substitude.com
osproxy.com
chineseproxy.org
unrestricter.com
proxyserver.online
vpnbypass.ml
pp.ua
untracable.org
cloudproxy.ga
zxingtai.com
websiteproxy.com
pinkxter.com
68.142.242.246
aceproxylist.com
getnewip.ml
hideipsurfer.ga
informer.com
unblocken.com
www.proxyauthor.com
proxyauthor.com
www.proxycreate.com
proxycreate.com
proxylister.org
www.proxylister.org
www.proxysubmission.com
surfhidden.gq
pandashop.ge
web-proxy.co.uk
newipnow.com
www.justevade.com
anonproxy.eu
ploxey.com
hideoxy.com
proxy.org
www.my-proxy.com
proxysitelist.net
bypassable.com
newwebproxies.blogspot.com
newwebproxies.blogspot.com.au
haproxy.org
wingate.com
accessproxy.science
my-proxy.com
mnot.net
oxylabs.io
intoproxy.com
alhea.com
proxy-n-vpn.com
newfreeproxy.com
proxybay.tv
maxiproxies.com
free-proxy.cz
charlesproxy.com
anonproxy.eu
webproxyproject.com
techtarget.com
squid-cache.org
your-freedom.net
bypassable.com
daproxy.biz
guireif.com
saravanos.org
123youtube.net
socks5proxsy.org
freehollandproxy.nl
vincentdekoning.nl
changeproxy.org
secureunblock.gq
proxyunlocker.cf
exodum.net
tbglenolife.fr
cphn.ga
proxyprogram.org
bestwebproxy.ml
daymarquez.com
coolproxy.biz
aui.su
anonproxy.eu
*.aui.su
www.proxyprogram.org
proxyunlocker.cf
secureunblock.gq
techwelkin.com
europeanproxy.com
proxy-power.com
formobile.com.au
2fastsurfer.com

COMMENT

BASE_URL = 'http://covenanteyes.com/my_account'
SERVERS  = %w[

]

servers = SERVERS

Capybara.javascript_driver = :webkit
Capybara.default_driver    = :webkit

Capybara.configure do |config|
  config.run_server = false
  config.app_host   = 'https://covenanteyes.com/'
end

Capybara::Webkit.configure do |config|
  config.allow_unknown_urls
end

include Capybara::DSL

visit '/myaccount/login/'

page.within('#sign_in_form') do
  fill_in "id_sign_in_username", with: ENV['CE_USERNAME']
  fill_in "id_sign_in_password", with: ENV['CE_PASSWORD']

  click_on "Sign in"
end

visit "/myaccount/filter/users/#{ENV['CE_FILTER_USERNAME']}/allow-block-lists"


page.within('.block_list') do
  servers.each do |server|
    begin
      fill_in 'filter_settings_add_blocked', with: server
      click_on "Add to List"
      puts server
      sleep 0.25
    rescue Capybara::Webkit::NodeNotAttachedError => e
      sleep 1
      retry
    end
  end
end

page.save_and_open_screenshot("./result.png")
